### ISSUE TITLE
Code optimization 

### ISSUE THREAD

**Issue by WafaBenyettou** [Yasserkaci/nails_store#2]
You need to optimize ur code more, for example in the MostOrdered.js you could have just simply used an array of data instead of hardcoding each item, create an array of objects to store the data and then map through it in that way, you can add or delete items way easier without banging your head against the wall every time you want to make a change + instead of CSS i highly advice you to switch into TailwindCSS as it works really well with react and is easy to use :) 

cc @madjide04 pull req brought me here lol

**Comment by Yasserkaci** [comment]
well for the  MostOrdered.js  i did it this way as a place holder only . in the final project i will have a card component and i will fech the data from the back-end but for now its just to fill the place cz we're still testing the design + i agree on the tailwindCSS part but i have a beginner who's new to coding and learning from my code so i had to keep it simple

Although, thank you so much i really appreciate it :D
